from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    question: str = Field(..., description="The legal question to ask the Guardian chatbot.")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The response generated by the LLM.")
    provider: str = Field(..., description="The LLM provider used for the response.")
    disclaimer: str = Field(..., description="Legal disclaimer regarding the advice provided.")
